services:
  web:
    build: .
    container_name: newproject_web
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:rw
      - ./data:/app/data:rw
      - ./models:/app/models:rw
    environment:
      - PYTHONUNBUFFERED=1
  restart: unless-stopped
  # Add health status passthrough if needed later (depends on Docker/compose version)
