services:
  caddy:
    image: caddy:2-alpine
    container_name: newproject_caddy_local
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/caddy/conf/Caddyfile.local:/etc/caddy/Caddyfile:ro
      - ./infra/caddy/data:/data
      - ./infra/caddy/config:/config
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
